export default {
    GET_PRODUCTS:'GET_PRODUCTS',
    GET_PRODUCTS_SUCCESS:'GET_PRODUCTS_SUCCESS',
    GET_PRODUCTS_FAILED:'GET_PRODUCTS_FAILED',

    ADD_TO_CART:'ADD_TO_CART',
    CHANGE_CART_VISIBILITY:'CHANGE_CART_VISIBILITY'
}